-- AlterTable
ALTER TABLE "User" ADD COLUMN "bio" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN "displayName" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN "firstName" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN "lastName" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN "location" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN "phone" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN "website" TEXT DEFAULT '';
